const eventsActionTypes = {
  FETCH_ALL_EVENTS_START: "FETCH_ALL_EVENTS_START",
  FETCH_ALL_EVENTS_SUCCESS: "FETCH_ALL_EVENTS_SUCCESS",
  FETCH_ALL_EVENTS_FAILED: "FETCH_ALL_EVENTS_FAILED",
};
export default eventsActionTypes;
